TebLocalPlannerROS:

 odom_topic: odom
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 max_samples: 500
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: True
 max_global_plan_lookahead_dist: 10
 global_plan_viapoint_sep: -1
 global_plan_prune_distance: 1
 exact_arc_length: False
 feasibility_check_no_poses: 2
 publish_feedback: False
    
 # Robot
         
 max_vel_x: 3.0
 max_vel_x_backwards: 0.2
 max_vel_y: 0.0
 max_vel_theta: 2.5                # the angular velocity is also bounded by min_turning_radius in case of a carlike robot (r = v / omega)
 acc_lim_x: 3.0
 acc_lim_theta: 3.0

 # ********************** Carlike robot parameters ********************
 min_turning_radius: 0.95        # Min turning radius of the carlike robot (compute value using a model or adjust with rqt_reconfigure manually)
 wheelbase: 0.4                 # Wheelbase of our robot
 cmd_angle_instead_rotvel: True # stage simulator takes the angle instead of the rotvel as input (twist message)
 # ********************************************************************

 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "line"
   radius: 0.2 # for type "circular"
   line_start: [0.0, 0.0] # for type "line"
   line_end: [0.4, 0.0] # for type "line"
   front_offset: 0.2 # for type "two_circles"
   front_radius: 0.2 # for type "two_circles"
   rear_offset: 0.2 # for type "two_circles"
   rear_radius: 0.2 # for type "two_circles"
   vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

 # GoalTolerance
    
 xy_goal_tolerance: 0.2                    #到达目标点时,在xy平面内与目标点的距离误差，以米为单位
 yaw_goal_tolerance: 0.1                   #允许的最终方向误差（弧度）
 free_goal_vel: False                      #消除目标速度限制，使机器人可以最大速度到达目标
 complete_global_plan: True
    
 # Obstacles
    
 min_obstacle_dist: 0.5                    # This value must also include our robot's expansion, since footprint_model is set to "line".与障碍物的最小期望距离（以米为单位）
 inflation_dist: 1.0                       #障碍物膨胀距离。此膨胀只是降低通过这些区域的优先级，不应当用此距离迫使车辆远离障碍物。
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 20

 dynamic_obstacle_inflation_dist: 0.6
 include_dynamic_obstacles: True 

 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 8

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 15.0                     #为惩罚函数增加一个小的安全余量，以实现硬约束近似
 obstacle_cost_exponent: 4 
 weight_max_vel_x: 4                       #满足最大允许平移速度的优化权重
 weight_max_vel_theta: 3                   #满足最大允许角速度的优化权重
 weight_acc_lim_x: 5                       #满足最大允许平移加速度的优化权重
 weight_acc_lim_theta: 3                   #满足最大允许角加速度的优化重量
 weight_kinematics_nh: 1000                #用于满足非完整运动学的优化权重（该参数必须很高，因为运动学方程构成了一个等式约束，即使值1000也不意味着由于与其他成本相比较小的“原始”成本值而导致的矩阵条件不佳） 。
 weight_kinematics_forward_drive: 1        #优化重量，迫使机器人仅选择前进方向（正向速度）。较小的重量（例如1.0）仍然允许向后行驶。
 weight_kinematics_turning_radius: 1       #优化重量，以实现最小转弯半径
 weight_optimaltime: 4                     # must be > 0收缩轨迹过渡/执行时间的优化权重
 weight_shortest_path: 0
 weight_obstacle: 100                      #优化重量以保持与障碍物的最小距离
 weight_inflation: 0.2                     #通胀惩罚的优化权重（应该很小）。
 weight_dynamic_obstacle: 10               # not in use yet
 weight_dynamic_obstacle_inflation: 0.2
 weight_viapoint: 1                        #优化权重，以最小化到通孔的距离（参考路径）。
 weight_adapt_factor: 2     #在每个外部TEB迭代中，一些特殊权重（当前为weight_obstacle）会通过此因子重复缩放（weight_new = weight_old * factor）。迭代增加权重而不是设置较大的先验值会导致底层优化问题的更好数值条件。



 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 max_number_classes: 4
 selection_cost_hysteresis: 1.0
 selection_prefer_initial_plan: 0.95
 selection_obst_cost_scale: 1.0
 selection_alternative_time_cost: False

 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 roadmap_graph_area_length_scale: 1.0
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_heading_threshold: 0.45
 switching_blocking_period: 0.0
 viapoints_all_candidates: True
 delete_detours_backwards: True
 max_ratio_detours_duration_best_duration: 3.0
 visualize_hc_graph: False
 visualize_with_time_as_z_axis_scale: False

# Recovery
 
 shrink_horizon_backup: True
 shrink_horizon_min_duration: 10
 oscillation_recovery: True
 oscillation_v_eps: 0.1
 oscillation_omega_eps: 0.1
 oscillation_recovery_min_duration: 10
 oscillation_filter_duration: 10
